rootProject.name = "chigirh-bc-notice"
include(":config")
include(":common")
include(":web")
include(":batch")
include(":application")
include(":domain")
include(":persistence")
include(":infra:mysql")
include(":infra:api")
include(":infra:mail")
